[book]
authors = ["Klas Segeljakt", "Frej Drejhammar"]
description = "Arc-Lang documentation."
multilingual = false
src = "src"
title = "Arc-Lang"

[build]
build-dir = "target"
create-missing = true

[preprocessor.grammar]
command = "./grammar/target/debug/grammar"
renderer = ["html"]

[preprocessor.syntax]
command = "./syntax/target/debug/syntax"
renderer = ["html"]
after = ["links"]

[preprocess.index]

[preprocess.links]

[preprocessor.bib]
title = "References"
bibliography = "references.bib"

[output.html]
default-theme = "rust"
no-section-label = true
git_repository_url = "www.github.com/cda-group/arc"
git_repository_icon = "fa-github"
mathjax-support = true
additional-css = ["style.css"]

[output.html.playpen]
editable = false
copy-js = false

[output.html.search]
enable = true

[output.linkcheck]
follow-web-links = false
warning-policy = "error"
