[package]
name = "remote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-runtime = { path = "../../" }
lazy_static                   = { version = "1.4.0" }
