[package]
name    = "macros"
version = "0.0.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote       = { version = "1.0.8" }
syn         = { version = "1.0.58", features = ["full", "visit-mut"] }
proc-macro2 = { version = "1.0.24" }
