[package]
name = "worker"
version = "0.0.0"
edition = "2021"

[dependencies]
shared        = { path = "../shared" }
axum          = { version = "0.6.3" }
clap          = { version = "4.1.3", features = ["derive"] }
futures       = { version = "0.3.25" }
serde         = { version = "1.0.152", features = ["derive"] }
tokio         = { version = "1.24.2", features = ["full"] }
tokio-futures = { version = "0.0.0" }
tokio-serde   = { version = "0.8.0", features = ["json"] }
tokio-stream  = { version = "0.1.11" }
tokio-util    = { version = "0.7.4", features = ["full"] }
tracing       = { version = "0.1.37" }
raw-cpuid     = { version = "10.6.0", features = ["serde"] }
num_cpus      = { version = "1.15.0" }
